name: Release Caller

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  call-workflow:
    permissions:
      contents: write
    uses: ac-clash/workflows/.github/workflows/release-called.yml@main
    secrets:
      token: ${{ secrets.TOKEN }}
